apiVersion: app.rjscy.cn/v1
kind: App
metadata:
  name: app1
spec:
  deploy:
    selector:
      matchLabels:
        app: app1
    template:
      metadata:
        name: sample1
        labels:
          app: app1
      spec:
        containers:
          - name: hello
            image: busybox
            command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
