apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-pod-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pod
  failurePolicy: Fail
  name: mapp.kb.io
  rules:
  - apiGroups:
    - app.rjscy.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
