
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-rjscy-cn-v1-app
  failurePolicy: Fail
  name: mapp.kb.io
  rules:
  - apiGroups:
    - app.rjscy.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apps

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-rjscy-cn-v1-app
  failurePolicy: Fail
  name: vapp.kb.io
  rules:
  - apiGroups:
    - app.rjscy.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apps
